module.exports = 
[{"equipmentCode":"35-2420907","equipmentNumber":56,"description":"Aliquam non mauris."},
{"equipmentCode":"39-7963379","equipmentNumber":35,"description":"Proin eu mi."},
{"equipmentCode":"39-2213383","equipmentNumber":57,"description":"Morbi porttitor lorem id ligula."},
{"equipmentCode":"79-7855767","equipmentNumber":1,"description":"Nulla mollis molestie lorem."},
{"equipmentCode":"92-0011370","equipmentNumber":86,"description":"Nam nulla."},
{"equipmentCode":"09-7524562","equipmentNumber":11,"description":"Sed sagittis."},
{"equipmentCode":"55-6077692","equipmentNumber":4,"description":"In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem."},
{"equipmentCode":"69-0825008","equipmentNumber":81,"description":"In quis justo."},
{"equipmentCode":"11-8487342","equipmentNumber":48,"description":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi."},
{"equipmentCode":"39-6445994","equipmentNumber":26,"description":"Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl."},
{"equipmentCode":"98-9713853","equipmentNumber":100,"description":"Etiam justo."},
{"equipmentCode":"25-2398791","equipmentNumber":33,"description":"Quisque id justo sit amet sapien dignissim vestibulum."},
{"equipmentCode":"81-9145153","equipmentNumber":16,"description":"Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl."},
{"equipmentCode":"05-5149289","equipmentNumber":84,"description":"Donec ut dolor."},
{"equipmentCode":"30-1800943","equipmentNumber":31,"description":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam."},
{"equipmentCode":"69-4822309","equipmentNumber":23,"description":"Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede."},
{"equipmentCode":"18-9990722","equipmentNumber":34,"description":"Morbi non lectus."},
{"equipmentCode":"99-4414407","equipmentNumber":47,"description":"Proin interdum mauris non ligula pellentesque ultrices."},
{"equipmentCode":"42-4121478","equipmentNumber":26,"description":"Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh."},
{"equipmentCode":"54-1336350","equipmentNumber":78,"description":"Duis at velit eu est congue elementum."},
{"equipmentCode":"48-6690428","equipmentNumber":17,"description":"Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc."},
{"equipmentCode":"02-9273096","equipmentNumber":71,"description":"Duis aliquam convallis nunc."},
{"equipmentCode":"09-8000422","equipmentNumber":20,"description":"Donec vitae nisi."},
{"equipmentCode":"51-9944702","equipmentNumber":41,"description":"Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo."},
{"equipmentCode":"79-3102540","equipmentNumber":87,"description":"Aenean lectus."},
{"equipmentCode":"49-1116273","equipmentNumber":42,"description":"Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla."},
{"equipmentCode":"27-6601721","equipmentNumber":18,"description":"Phasellus in felis."},
{"equipmentCode":"34-4370700","equipmentNumber":73,"description":"Phasellus id sapien in sapien iaculis congue."},
{"equipmentCode":"39-4065976","equipmentNumber":25,"description":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit."},
{"equipmentCode":"42-8842010","equipmentNumber":43,"description":"Cras non velit nec nisi vulputate nonummy."}]